GET /api/wallet/balance/1 HTTP/1.1
Accept: */*
Host: localhost:3000


###

POST /api/wallet/money HTTP/1.1
Accept: */*
Content-Type: application/json
Host: localhost:3000
Content-Length: 33

{
  "user_id": 1,
  "amount": 1
}

###

GET /api/audit/ HTTP/1.1
Accept: */*
Host: localhost:3001

